"""init tables

Revision ID: 3f4accafe7d7
Revises: 
Create Date: 2024-11-21 08:50:17.375413

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f4accafe7d7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("prefix", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_locations_name"), "locations", ["name"], unique=True
    )
    op.create_index(
        op.f("ix_locations_prefix"), "locations", ["prefix"], unique=True
    )
    op.create_table(
        "ports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("port_number", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("port_number"),
    )
    op.create_table(
        "vlans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vlan", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vlan"),
    )
    op.create_table(
        "core_switches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("snmp_oid", sa.String(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_core_switches_comment"),
        "core_switches",
        ["comment"],
        unique=True,
    )
    op.create_index(
        op.f("ix_core_switches_ip_address"),
        "core_switches",
        ["ip_address"],
        unique=True,
    )
    op.create_table(
        "switches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("snmp_oid", sa.String(), nullable=False),
        sa.Column("core_switch_ip", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["core_switch_ip"],
            ["core_switches.ip_address"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_switches_ip_address"), "switches", ["ip_address"], unique=True
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workplace_number", sa.String(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("mac", sa.String(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("pc_name", sa.String(), nullable=True),
        sa.Column("nau_user", sa.String(), nullable=True),
        sa.Column("domain_user", sa.String(), nullable=True),
        sa.Column("remote_control", sa.String(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("update_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("switch_id", sa.Integer(), nullable=False),
        sa.Column("vlan_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["switch_id"],
            ["switches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vlan_id"],
            ["vlans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mac"),
        sa.UniqueConstraint("workplace_number"),
    )
    op.create_table(
        "switch_ports",
        sa.Column("switch_id", sa.Integer(), nullable=False),
        sa.Column("port_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["port_id"],
            ["ports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["switch_id"],
            ["switches.id"],
        ),
        sa.PrimaryKeyConstraint("switch_id", "port_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("switch_ports")
    op.drop_table("devices")
    op.drop_index(op.f("ix_switches_ip_address"), table_name="switches")
    op.drop_table("switches")
    op.drop_index(
        op.f("ix_core_switches_ip_address"), table_name="core_switches"
    )
    op.drop_index(op.f("ix_core_switches_comment"), table_name="core_switches")
    op.drop_table("core_switches")
    op.drop_table("vlans")
    op.drop_table("ports")
    op.drop_index(op.f("ix_locations_prefix"), table_name="locations")
    op.drop_index(op.f("ix_locations_name"), table_name="locations")
    op.drop_table("locations")
    # ### end Alembic commands ###
