"""create_test_tables

Revision ID: c69ad7c2b385
Revises: 94e61c74c0ac
Create Date: 2024-10-20 20:03:10.070406

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c69ad7c2b385"
down_revision: Union[str, None] = "94e61c74c0ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "core_switches",
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_core_switches_ip_address"),
        "core_switches",
        ["ip_address"],
        unique=True,
    )
    op.create_index(op.f("ix_core_switches_name"), "core_switches", ["name"], unique=True)
    op.create_table(
        "switches",
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("core_switch_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["core_switch_id"],
            ["core_switches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_switches_ip_address"), "switches", ["ip_address"], unique=True)
    op.create_table(
        "devices",
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("mac", sa.String(), nullable=False),
        sa.Column("vlan", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=False),
        sa.Column("switch_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["switch_id"],
            ["switches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("devices")
    op.drop_index(op.f("ix_switches_ip_address"), table_name="switches")
    op.drop_table("switches")
    op.drop_index(op.f("ix_core_switches_name"), table_name="core_switches")
    op.drop_index(op.f("ix_core_switches_ip_address"), table_name="core_switches")
    op.drop_table("core_switches")
    # ### end Alembic commands ###
