"""init

Revision ID: 24f2d1eca0e9
Revises: 
Create Date: 2024-10-28 15:00:17.775123

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24f2d1eca0e9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "core_switches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("snmp_oid", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_core_switches_ip_address"),
        "core_switches",
        ["ip_address"],
        unique=True,
    )
    op.create_index(op.f("ix_core_switches_name"), "core_switches", ["name"], unique=True)
    op.create_table(
        "excluded_ports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("port_number", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("port_number"),
    )
    op.create_table(
        "switches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("snmp_oid", sa.String(), nullable=False),
        sa.Column("core_switch_ip", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["core_switch_ip"],
            ["core_switches.ip_address"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_switches_ip_address"), "switches", ["ip_address"], unique=True)
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workplace_number", sa.String(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("mac", sa.String(), nullable=False),
        sa.Column("vlan", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("update_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("switch_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["switch_id"],
            ["switches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workplace_number"),
    )
    op.create_table(
        "switch_excluded_ports",
        sa.Column("switch_id", sa.Integer(), nullable=False),
        sa.Column("excluded_port_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["excluded_port_id"],
            ["excluded_ports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["switch_id"],
            ["switches.id"],
        ),
        sa.PrimaryKeyConstraint("switch_id", "excluded_port_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("switch_excluded_ports")
    op.drop_table("devices")
    op.drop_index(op.f("ix_switches_ip_address"), table_name="switches")
    op.drop_table("switches")
    op.drop_table("excluded_ports")
    op.drop_index(op.f("ix_core_switches_name"), table_name="core_switches")
    op.drop_index(op.f("ix_core_switches_ip_address"), table_name="core_switches")
    op.drop_table("core_switches")
    # ### end Alembic commands ###
