"""add switch_id to devices

Revision ID: 29ff9609360a
Revises: 769e0f92c626
Create Date: 2024-11-14 22:12:17.989567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29ff9609360a"
down_revision: Union[str, None] = "769e0f92c626"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices", sa.Column("switch_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "devices", "switches", ["switch_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "devices", type_="foreignkey")
    op.drop_column("devices", "switch_id")
    # ### end Alembic commands ###
